server:
  compression:
    enabled: true
  http2:
    enabled: true
  port: 8001
spring:
  datasource:
    username: wcq
    password: Wcq123456
    url: jdbc:mysql://rm-2ze853397mhy2yl3nio.mysql.rds.aliyuncs.com:3306/shower?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
  application:
    name: shower-01
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cache:
    type: simple
mybatis:
  mapper-locations: classpath*:/mappers/*Mapper.xml

logging:
  level:
    org.minbox.framework.api.boot.plugin.logging: debug
    org.yuan.boot.shower.db.mapper: debug

api:
  boot:
    logging:
      admin:
        format-console-log-json: true
      show-console-log: true
      format-console-log-json: true
    security:
      away: jdbc
    quartz:
      job-store-type: memory

wx:
  miniapp:
    appid:
    aes-key:
    msg-data-format: JSON
    secret:
    token:
  pay:
    app-id:
    key-path:
    mch-id:
    mch-key:
    sub-app-id:
    sub-mch-id:
  mp:
    aes-key:
    app-id:
    config-storage:
      type: memory
    secret:
    token: